version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - WORKERS=2
      - ALLOWED_ORIGINS=http://localhost,http://127.0.0.1,http://localhost:8080,http://127.0.0.1:8080
    expose:
      - "8000"

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    environment:
      # Use same-origin in production (proxied), so keep empty
      - VITE_BACKEND_URL=
    expose:
      - "80"
    depends_on:
      - server

  proxy:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - server
