services:
  - type: web
    name: monopoly-online
    env: docker
    plan: free
    rootDir: .
    dockerCommand: ""
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: WORKERS
        value: "1"
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: AUTH_SECRET
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
    # Use the API Dockerfile which also bakes the static frontend
    dockerfilePath: server/Dockerfile
    # Ports inferred from EXPOSE; keep default
