services:
  - type: web
    name: monopoly-online
    env: docker
    plan: free
    rootDir: .
    dockerCommand: ""
    autoDeploy: true
  healthCheckPath: /healthz
    envVars:
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: WORKERS
        value: "1"
    # Render will build using the Dockerfile in server/ by default only if set; we specify here
    dockerfilePath: server/Dockerfile
    # Ports inferred from EXPOSE; keep default
